# Generated by Django 3.2 on 2021-07-23 16:00

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_img', models.ImageField(blank=True, default='author/img3.jpg', null=True, upload_to='author/')),
                ('title', models.CharField(max_length=254)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_tur', models.CharField(help_text='turni tanlang fashion,event,wedding,corporate ', max_length=255)),
                ('rasm', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=240)),
                ('tur', models.CharField(max_length=254)),
                ('desc_title', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=254)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('cliyent', models.CharField(max_length=250)),
                ('technology', models.CharField(max_length=100)),
                ('date_create', models.DateField()),
                ('visit_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_title', models.CharField(max_length=250)),
                ('desc', models.CharField(max_length=254)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('cliyent', models.CharField(max_length=250)),
                ('technology', models.CharField(max_length=100)),
                ('date_create', models.DateField()),
                ('visit_url', models.URLField(blank=True, null=True)),
                ('project_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectdetail', to='my_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='my_app.posttoproject')),
            ],
        ),
    ]
